spring:
  data:
    mongodb:
      username: mongo
      password: fuwo3WTOuRL1mVbhpb1J
      port: 6328
      host: containers-us-west-70.railway.app
      database: khedma
      authentication-database: admin
      auto-index-creation: true
server:
  port: 9630