spring:
  data:
    mongodb:
      username: mongo
      password: L7iVCe199xB6nmwBXQXn
      port: 5819
      host: containers-us-west-114.railway.app
      database: khedma
      authentication-database: admin
      auto-index-creation: true
server:
  port: 9630