spring:
  data:
    mongodb:
      username: Y.admin
      password: admin
      port: 27017
      host: localhost
      database: khedma
      authentication-database: admin
      auto-index-creation: true
server:
  port: 9631

